/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasExtra;

import java.sql.*;
import VentanasExtra.Consultas;
import MenusTablas.Cupon;
import MenusTablas.Oferta;
import MenusTablas.Opinion;
import MenusTablas.Producto;
import MenusTablas.Socio;
import MenusTablas.Ticket;
import MenusTablas.Tienda;
import MenusTablas.Trabajador;

/**
 *
 * @author razvanvc
 */
public class Main_Menu extends javax.swing.JFrame {

    public static Connection conexion;
    /**
     * Creates new form Vista_Gestor
     */
    
    public Main_Menu(Connection c) {
        Main_Menu.conexion = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Tienda = new javax.swing.JButton();
        btn_Ticket = new javax.swing.JButton();
        btn_Trabajador = new javax.swing.JButton();
        btn_Opinion = new javax.swing.JButton();
        btn_Socio = new javax.swing.JButton();
        btn_Producto = new javax.swing.JButton();
        btn_Oferta = new javax.swing.JButton();
        btn_Cupon = new javax.swing.JButton();
        btn_Consulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Tienda.setText("Tienda");
        btn_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TiendaActionPerformed(evt);
            }
        });

        btn_Ticket.setText("Ticket");
        btn_Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TicketActionPerformed(evt);
            }
        });

        btn_Trabajador.setText("Trabajador");
        btn_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrabajadorActionPerformed(evt);
            }
        });

        btn_Opinion.setText("Opinion");
        btn_Opinion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpinionActionPerformed(evt);
            }
        });

        btn_Socio.setText("Socio");
        btn_Socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SocioActionPerformed(evt);
            }
        });

        btn_Producto.setText("Producto");
        btn_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductoActionPerformed(evt);
            }
        });

        btn_Oferta.setText("Oferta");
        btn_Oferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OfertaActionPerformed(evt);
            }
        });

        btn_Cupon.setText("Cupon");
        btn_Cupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CuponActionPerformed(evt);
            }
        });

        btn_Consulta.setText("Consulta");
        btn_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Socio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Opinion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Oferta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cupon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Socio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Oferta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cupon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_Opinion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(624, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TiendaActionPerformed
        // TODO add your handling code here:
        Tienda ventana = new Tienda(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_TiendaActionPerformed

    private void btn_TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TicketActionPerformed
        // TODO add your handling code here:
        Ticket ventana = new Ticket(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_TicketActionPerformed

    private void btn_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrabajadorActionPerformed
        // TODO add your handling code here:
        Trabajador ventana = new Trabajador(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_TrabajadorActionPerformed

    private void btn_OpinionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpinionActionPerformed
        // TODO add your handling code here:
        Opinion ventana = new Opinion(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_OpinionActionPerformed

    private void btn_SocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SocioActionPerformed
        // TODO add your handling code here:
        Socio ventana = new Socio(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_SocioActionPerformed

    private void btn_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductoActionPerformed
        // TODO add your handling code here:
        Producto ventana = new Producto(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_ProductoActionPerformed

    private void btn_OfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OfertaActionPerformed
        // TODO add your handling code here:
        Oferta ventana = new Oferta(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_OfertaActionPerformed

    private void btn_CuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CuponActionPerformed
        // TODO add your handling code here:
        Cupon ventana = new Cupon(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_CuponActionPerformed

    private void btn_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultaActionPerformed
        // TODO add your handling code here:
        Consultas ventana = new Consultas(conexion);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu(conexion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JButton btn_Cupon;
    private javax.swing.JButton btn_Oferta;
    private javax.swing.JButton btn_Opinion;
    private javax.swing.JButton btn_Producto;
    private javax.swing.JButton btn_Socio;
    private javax.swing.JButton btn_Ticket;
    private javax.swing.JButton btn_Tienda;
    private javax.swing.JButton btn_Trabajador;
    // End of variables declaration//GEN-END:variables
}
